version: "3.7"

services:
  mongo_db:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db

  redis:
    image: redis:6.2.12-alpine
    restart: always
    ports:
      - 6379:6379

  expense-tracker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: expense-tracker-service
    volumes:
      - ./:/app
    depends_on:
      - "mongo_db"
      - "redis"
    ports:
      - 5000:5000

volumes:
  mongodb_data:
